import { ActiveLink } from "@/components/ActiveLink";

export const ComponentsLinks = () => {
  return (
    <div className="SideMenu-menuSection">
      <h2>
        <label htmlFor="menu-components" className="SideMenu-menuHeading">
          Components
        </label>
      </h2>
      <div className="Collapse-content">
        <input type="checkbox" hidden id="menu-components" defaultChecked />

        <h3 className="SideMenu-menuSubHeading">Display</h3>
        <ul>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#content"
            >
              Content
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#avatar"
            >
              Avatar
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#badge"
            >
              Badge
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#card"
            >
              Card
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#chip"
            >
              Chip
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#collapse"
            >
              Collapse
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#tooltip"
            >
              Tooltip
            </ActiveLink>
          </li>
        </ul>

        <h3 className="SideMenu-menuSubHeading">feedback</h3>
        <ul>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#alert"
            >
              Alert
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#modal"
            >
              Modal
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#progress"
            >
              Progress
            </ActiveLink>
          </li>
        </ul>

        <h3 className="SideMenu-menuSubHeading">input</h3>
        <ul>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#button"
            >
              Button
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#control"
            >
              Control
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#input"
            >
              Input
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#textarea"
            >
              Textarea
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#select"
            >
              Select
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#switch"
            >
              Switch
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#checkbox"
            >
              Checkbox
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#radio"
            >
              Radio
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#slider"
            >
              Slider
            </ActiveLink>
          </li>
        </ul>

        <h3 className="SideMenu-menuSubHeading">navigation</h3>
        <ul>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#breadcrumbs"
            >
              Breadcrumbs
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#drawer"
            >
              Drawer
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#dropdown"
            >
              Dropdown
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#menu"
            >
              Menu
            </ActiveLink>
          </li>
          <li>
            <ActiveLink
              className="SideMenu-menuItem"
              href="/packages/guvam.com/app/(website)/docs/components#pagination"
            >
              Pagination
            </ActiveLink>
          </li>
        </ul>
      </div>
    </div>
  );
};
